import Head from "next/head";
import Map from "@/components/Map";
import Search from "@/components/search/Search";
import Stack from "@/components/stack/Stack";
import Card from "@/components/stack/card/Card";
import NumbersCard from "@/components/stack/card/NumbersCard";
import { useState } from "react";
import BackButton from "@/components/stack/BackButton";
import { Result, Selection } from "@/common-types";

export default function Home() {
  const [selected, setSelected] = useState<Selection>(null);
  const [query, setQuery] = useState("");
  const [searchBarExpanded, setSearchBarExpanded] = useState(false);
  const [searchResultVisible, setSearchResultVisible] = useState(false);

  function searchBarOnClick() {
    setSearchBarExpanded(true);
    setSearchResultVisible(true);
  }

  function searchBarOnChange(e: React.ChangeEvent<HTMLInputElement>) {
    setQuery(e.target.value);
  }

  function resultOnClick(result: Result) {
    setSelected(result.value as unknown as Selection);
  }

  function backButtonOnClick() {
    setSelected(null);
  }

  function mapOnClick() {
    if (query === "") setSearchBarExpanded(false);
    setSearchResultVisible(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <main className="flex h-full w-full flex-col items-center justify-center overflow-hidden">
        <Map selected={selected} onClick={mapOnClick} />
        {selected === null ? (
          <Search
            query={query}
            searchBarExpanded={searchBarExpanded}
            searchResultVisible={searchResultVisible}
            searchBarOnClick={searchBarOnClick}
            searchBarOnChange={searchBarOnChange}
            resultOnClick={resultOnClick}
          />
        ) : (
          <Stack selected={selected} backButtonOnClick={backButtonOnClick}>
            <NumbersCard
              numbers={[
                { value: 39, header: "No. of stations" },
                { value: 7.12, header: "Route length" },
                { value: 30, header: "Avg. waiting time" },
                { value: 30, header: "Avg. waiting time" },
              ]}
            />
            <Card header="Heart Rate">
              <p className="w-full">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </Card>
            <Card header="Avg. Activity" />
            <Card />
          </Stack>
        )}
        <div className="absolute right-0 top-0 flex max-h-full flex-col gap-5 p-5">
          <BackButton />
        </div>
      </main>
    </>
  );
}
